version: "2.22"
services:
  pomoservice:
    container_name: pomowork-service
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOSTNAME: "${DATABASE_HOSTNAME}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_DAYS: "${ACCESS_TOKEN_EXPIRE_DAYS}"
      REFRESH_TOKEN_EXPIRE_DAYS: "${REFRESH_TOKEN_EXPIRE_DAYS}"
    networks:
        - pomowork_net
networks:
  pomowork_net:
