"""users and project relationship created

Revision ID: 85021950b739
Revises: f83d5d1153c7
Create Date: 2023-07-04 21:40:51.964119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85021950b739'
down_revision = 'f83d5d1153c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
