"""removed card table

Revision ID: 9f00c8ad9cef
Revises: 85021950b739
Create Date: 2023-10-26 01:19:19.902035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f00c8ad9cef'
down_revision = '85021950b739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pomo_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('collected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='cards_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    # ### end Alembic commands ###
