"""pomo table removed

Revision ID: b0e5227afb6d
Revises: b2d996358383
Create Date: 2023-06-29 21:01:32.277721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e5227afb6d'
down_revision = 'b2d996358383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pomodoro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='pomodoro_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pomodoro_pkey')
    )
    # ### end Alembic commands ###
